### ISSUE TITLE
higherhrnet？

### ISSUE THREAD

**Issue by henbucuoshanghai** [HRNet/HRNet-MaskRCNN-Benchmark#5]
higherhrnet？ the last stage featuremap aggregation???it means what??

aggregation it means add? or featuremap concate????

and tagmaps it means???? I dont konw tagmap

**Comment by wondervictor** [comment]
Hi, HigherHRNet is here [Higher-HRNet-Human-Pose-Estimation](https://github.com/HRNet/Higher-HRNet-Human-Pose-Estimation)

**Comment by henbucuoshanghai** [comment]
I have read the paper,but I dont understand sth.

**Comment by henbucuoshanghai** [comment]
the last stage featuremap aggregation???it means what??

aggregation it means add? or featuremap concate????

and tagmaps it means???? I dont konw tagmap

**Comment by wondervictor** [comment]
@henbucuoshanghai  This repo is **HRNet for Object Detection**.
As for feature aggregation in HRNetV2p, we use concatenation.
What's `tagmaps/tagmap`?

**Comment by henbucuoshanghai** [comment]
Tagmaps are trained differently from heatmaps in High-erHRNet. We only predict tagmaps at the lowest resolution,instead  of  using  all  resolutions.   This  is  because  learningtagmaps requires global reasoning and it is more suitable topredict tagmaps in lower resolution.  Empirically, we alsofind higher resolutions do not learn to predict tagmaps welland even do not converge. Thus, we follow [22] to train thetagmaps on feature maps at14resolution of input image

**Comment by henbucuoshanghai** [comment]
Tagmaps  it means???????

**Comment by wondervictor** [comment]
@henbucuoshanghai  Your problem has nothing to do with this repo. This repo is for **Object Detection** not **Pose Estimation**

**Comment by henbucuoshanghai** [comment]
ok    i see,thanks
